from ex1 import HealingCreatureFactory, TransformCreatureFactory

if __name__ == "__main__":
    print("Testing Creature with healing capability\n base:")
    healing_factory: HealingCreatureFactory = HealingCreatureFactory()
    healing_base = healing_factory.create_base()
    print(healing_base.describe())
    print(healing_base.attack())
    print(healing_base.heal())
    print(" evolved:")
    healing_evolved = healing_factory.create_evolved()
    print(healing_evolved.describe())
    print(healing_evolved.attack())
    print(healing_evolved.heal())

    print("Testing Creature with transform capability\n base:")
    cap_factory: TransformCreatureFactory = TransformCreatureFactory()
    cap_base = cap_factory.create_base()
    print(cap_base.describe())
    print(cap_base.attack())
    print(cap_base.transform())
    print(cap_base.attack())
    print(cap_base.revert())
    print(" evolved:")
    cap_evolved = cap_factory.create_evolved()
    print(cap_base.describe())
    print(cap_base.attack())
    print(cap_base.transform())
    print(cap_base.attack())
    print(cap_base.revert())
    print(cap_base.attack())
